USE adlister_db;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
username VARCHAR (25) NOT NULL,
email VARCHAR (50) NOT NULL,
password VARCHAR (30) NOT NULL,
PRIMARY KEY (id)
);